### ISSUE TITLE
i am getting this error "checkout.js:40 Uncaught TypeError: Cannot read properties of undefined (reading 'deliveryDays')   and i have exactly followed the video i dont know whats wrong

### ISSUE THREAD

**Issue by uzairhafiz8** [SuperSimpleDev/javascript-course#148]
i am getting this error in console:

checkout.js:40 Uncaught TypeError: Cannot read properties of undefined (reading 'deliveryDays')
    at checkout.js:40:47
    at Array.forEach (<anonymous>)
    at renderOrderSummary (checkout.js:13:8)
    at checkout.js:203:1

i have attached the picture showing where it originates
![deliverydayserror](https://github.com/user-attachments/assets/a82cb2cc-12ff-433f-a480-babd9db4c152)

also if anyone wanna get in touch, help explain it or do the rest of the project together, here is my discord:willbettelheim6027

**Comment by Fz-Faiz** [comment]
You can try **localStorage.clear()** in **console**
[
![localStorage clear](https://github.com/user-attachments/assets/c4a02077-3962-4387-bf91-5c87079e6d98)
]

**Comment by banda-shri1998** [comment]
adding `debugger` before the line where error occurs while checking flow of execution becomes much easier to resolve by you own

**Comment by osmvenkat** [comment]
> i am getting this error in console:
> 
> checkout.js:40 Uncaught TypeError: Cannot read properties of undefined (reading 'deliveryDays') at checkout.js:40:47 at Array.forEach () at renderOrderSummary (checkout.js:13:8) at checkout.js:203:1
> 
> i have attached the picture showing where it originates ![deliverydayserror](https://private-user-images.githubusercontent.com/177337323/366159600-a82cb2cc-12ff-433f-a480-babd9db4c152.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODYyMzMsIm5iZiI6MTczMDM4NTkzMywicGF0aCI6Ii8xNzczMzczMjMvMzY2MTU5NjAwLWE4MmNiMmNjLTEyZmYtNDMzZi1hNDgwLWJhYmQ5ZGI0YzE1Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNDQ1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzFjNTBhYWYyNzVlYWI4MjA3MDJhN2JkMmFlOTVlMWM3N2Q1OTJmNTk4NWMzODg0Yjg4OGI1ZTNmMmQ2NTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mOdkhQp9HyaSu6TZXZ0j4O03GTUHrfSPTK_td4Ch--0)
> 
> also if anyone wanna get in touch, help explain it or do the rest of the project together, here is my discord:willbettelheim6027

SAME PROBLEM WITH ME DO  YOU FIND SOLUTION

**Comment by banda-shri1998** [comment]
unable to find you DISCORD here my Discord username : rockingshri27

> > i am getting this error in console:
> > checkout.js:40 Uncaught TypeError: Cannot read properties of undefined (reading 'deliveryDays') at checkout.js:40:47 at Array.forEach () at renderOrderSummary (checkout.js:13:8) at checkout.js:203:1
> > i have attached the picture showing where it originates ![deliverydayserror](https://private-user-images.githubusercontent.com/177337323/366159600-a82cb2cc-12ff-433f-a480-babd9db4c152.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODYyMzMsIm5iZiI6MTczMDM4NTkzMywicGF0aCI6Ii8xNzczMzczMjMvMzY2MTU5NjAwLWE4MmNiMmNjLTEyZmYtNDMzZi1hNDgwLWJhYmQ5ZGI0YzE1Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNDQ1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzFjNTBhYWYyNzVlYWI4MjA3MDJhN2JkMmFlOTVlMWM3N2Q1OTJmNTk4NWMzODg0Yjg4OGI1ZTNmMmQ2NTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mOdkhQp9HyaSu6TZXZ0j4O03GTUHrfSPTK_td4Ch--0)
> > also if anyone wanna get in touch, help explain it or do the rest of the project together, here is my discord:willbettelheim6027
> 
> SAME PROBLEM WITH ME DO YOU FIND SOLUTION

**Comment by Roopam-98** [comment]
heyy!! Check if you have imported deliveryOptions correctly! This simply means your current file thinks that deliveryDays doesn't exist which could be import issue or spelling issue of the property!

**Comment by banda-shri1998** [comment]
[Instagram](https://www.instagram.com/banda.shri/)
here is my insta ID to contact me so we can solve together

**Comment by Roopam-98** [comment]
> [Instagram](https://www.instagram.com/banda.shri/) here is my insta ID to contact me so we can solve together

Could you share your email? Or maybe your github repo used or amazon clone

**Comment by banda-shri1998** [comment]
@Roopam-98  
heres my gmail :- [banda.shri2710@gmail.com](mailto:banda.shri2710@gmail.com)

**Comment by ElementalcodeIn** [comment]
Hii... Everyone, so this is the solution of this Error.

The error `Cannot read properties of undefined (reading 'deliveryDays')` indicates that 

deliveryOption is `undefined` at line 32 in checkout.js

This means that the deliveryOptionId from cartItem does not match any id in deliveryOptions.

To fix this, you should add a check to ensure deliveryOption is found before trying to access its properties. Here's the updated code:

...
cart.forEach((cartItem) => {
  const productId = cartItem.productId;

  let matchingProduct;

  products.forEach((product) => {
    if (product.id === productId) {
      matchingProduct = product;
    }
  });

  const deliveryOptionId = cartItem.deliveryOptionsId;

  let deliveryOption;

  deliveryOptions.forEach((option) => {
    if (option.id === deliveryOptionId) {
      deliveryOption = option;
    }
  });

  if (!deliveryOption) {
    console.error(`Delivery option with id ${deliveryOptionId} not found`);
    return;
  }

  const today = dayjs();
  const deliveryDate = today.add(deliveryOption.deliveryDays, "days");
  const dateString = deliveryDate.format('dddd, MMMM D');

  cartSummaryHTMl += `
  <div class="cart-item-container js-cart-item-container-${matchingProduct.id}"> 
    <div class="delivery-date">
      Delivery date: ${dateString}
    </div>
    ...
  `;
});
...


This will log an error message if a deliveryOption is not found and prevent the code from trying to access properties of `undefined`.

Hope it will help you all and happy coding 👍

**Comment by Georgeikani** [comment]
I had same issues, was stocked for about 3 days, the solution is 
const deliveryDate = today.add(deliveryOptions.deliveryDays, 'days'); they should be an s on the deliveryOption. 
then if it shows again, dont delete the s, just use this command on the console
localStorage.clear()


//updating delivery date to the actual date.
    const deliveryOptionsId = cartItem.deliveryOptionsId;
    let deliveryOption; 
    deliveryOptions.forEach((Option) =>{
      if(Option.id === deliveryOptionsId){
        deliveryOption = Option
      }
    });

    const today = dayjs();
     const deliveryDate = today.add(deliveryOptions.deliveryDays,'days');  
      const dateString = deliveryDate.format(
        'dddd, MMMM D');

**Comment by Ishaprof0510** [comment]
> I had same issues, was stocked for about 3 days, the solution is const deliveryDate = today.add(deliveryOptions.deliveryDays, 'days'); they should be an s on the deliveryOption. then if it shows again, dont delete the s, just use this command on the console localStorage.clear()
> 
> //updating delivery date to the actual date. const deliveryOptionsId = cartItem.deliveryOptionsId; let deliveryOption; deliveryOptions.forEach((Option) =>{ if(Option.id === deliveryOptionsId){ deliveryOption = Option } });
> 
> ```
> const today = dayjs();
>  const deliveryDate = today.add(deliveryOptions.deliveryDays,'days');  
>   const dateString = deliveryDate.format(
>     'dddd, MMMM D');
> ```

Thank You. It finally helped. I used "deliveryOption.deliveryDays" instead of "deliveryOptions.deliveryDays". Such a relief. But, now I am getting an error with my radio button, I am unable to select any option for the delivery :(.

Can you help please?

**Comment by Bami97** [comment]
I have tried all solutions listed but none worked, can someone please help.

**Comment by Bami97** [comment]
> > I had same issues, was stocked for about 3 days, the solution is const deliveryDate = today.add(deliveryOptions.deliveryDays, 'days'); they should be an s on the deliveryOption. then if it shows again, dont delete the s, just use this command on the console localStorage.clear()
> > //updating delivery date to the actual date. const deliveryOptionsId = cartItem.deliveryOptionsId; let deliveryOption; deliveryOptions.forEach((Option) =>{ if(Option.id === deliveryOptionsId){ deliveryOption = Option } });
> > ```
> > const today = dayjs();
> >  const deliveryDate = today.add(deliveryOptions.deliveryDays,'days');  
> >   const dateString = deliveryDate.format(
> >     'dddd, MMMM D');
> > ```
> 
> Thank You. It finally helped. I used "deliveryOption.deliveryDays" instead of "deliveryOptions.deliveryDays". Such a relief. But, now I am getting an error with my radio button, I am unable to select any option for the delivery :(.
> 
> Can you help please?


Hey Ishaprof0510, have you fixed this?
