### ISSUE TITLE
i spent over 3 days over 18hours to fix this but i can't pls help me to fix this on lesson 14

### ISSUE THREAD

**Issue by nurhusenm** [SuperSimpleDev/javascript-course#84]
here is what am facing it in the console tab the check out page is not working pls simon simplify the tech world
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at checkout.js:20:48
    at Array.forEach (<anonymous>)
    at checkout.js:7:6

**Comment by MrItzreal** [comment]
Hey, please upload your code. We can't troubleshoot the issue without seeing all the details. While you've shown us the console error, we still need to see your code itself. It's possible there's a typo, as I've followed all of his videos, including the latest one (number 16), and haven't encountered any problems. If you want check my git commits since I made them as Simon was doing them.

**Comment by nurhusenm** [comment]
> Hey, please upload your code. We can't troubleshoot the issue without seeing all the details. While you've shown us the console error, we still need to see your code itself. It's possible there's a typo, as I've followed all of his videos, including the latest one (number 16), and haven't encountered any problems. If you want check my git commits since I made them as Simon was doing them.

which file should i uplaod as u know there is alot of files here is the checkout.html file code`<!DOCTYPE html>
<html>
  <head>
    <title>Checkout</title>

    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    
    <link rel="stylesheet" href="styles/shared/general.css">
    <link rel="stylesheet" href="styles/pages/checkout/checkout-header.css">
    <link rel="stylesheet" href="styles/pages/checkout/checkout.css">
  </head>
  <body>
    <div class="checkout-header">
      <div class="header-content">
        <div class="checkout-header-left-section">
          <a href="amazon.html">
            <img class="amazon-logo" src="images/amazon-logo.png">
            <img class="amazon-mobile-logo" src="images/amazon-mobile-logo.png">
          </a>
        </div>

        <div class="checkout-header-middle-section">
          Checkout (<a class="return-to-home-link"
            href="amazon.html">3 items</a>)
        </div>

        <div class="checkout-header-right-section">
          <img src="images/icons/checkout-lock-icon.png">
        </div>
      </div>
    </div>

    <div class="main">
      <div class="page-title">Review your order</div>

      <div class="checkout-grid">
        <div class="order-summary js-order-summary">
        </div>

        <div class="payment-summary">
          <div class="payment-summary-title">
            Order Summary
          </div>

          <div class="payment-summary-row">
            <div>Items (3):</div>
            <div class="payment-summary-money">$42.75</div>
          </div>

          <div class="payment-summary-row">
            <div>Shipping &amp; handling:</div>
            <div class="payment-summary-money">$4.99</div>
          </div>

          <div class="payment-summary-row subtotal-row">
            <div>Total before tax:</div>
            <div class="payment-summary-money">$47.74</div>
          </div>

          <div class="payment-summary-row">
            <div>Estimated tax (10%):</div>
            <div class="payment-summary-money">$4.77</div>
          </div>

          <div class="payment-summary-row total-row">
            <div>Order total:</div>
            <div class="payment-summary-money">$52.51</div>
          </div>

          <button class="place-order-button button-primary">
            Place your order
          </button>
        </div>
      </div>
    </div>

    <script type="module" src="scripts/checkout.js"></script>
  </body>
</html>`

and the checkout.js file `<!DOCTYPE html>
<html>
  <head>
    <title>Checkout</title>

    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    
    <link rel="stylesheet" href="styles/shared/general.css">
    <link rel="stylesheet" href="styles/pages/checkout/checkout-header.css">
    <link rel="stylesheet" href="styles/pages/checkout/checkout.css">
  </head>
  <body>
    <div class="checkout-header">
      <div class="header-content">
        <div class="checkout-header-left-section">
          <a href="amazon.html">
            <img class="amazon-logo" src="images/amazon-logo.png">
            <img class="amazon-mobile-logo" src="images/amazon-mobile-logo.png">
          </a>
        </div>

        <div class="checkout-header-middle-section">
          Checkout (<a class="return-to-home-link"
            href="amazon.html">3 items</a>)
        </div>

        <div class="checkout-header-right-section">
          <img src="images/icons/checkout-lock-icon.png">
        </div>
      </div>
    </div>

    <div class="main">
      <div class="page-title">Review your order</div>

      <div class="checkout-grid">
        <div class="order-summary js-order-summary">
        </div>

        <div class="payment-summary">
          <div class="payment-summary-title">
            Order Summary
          </div>

          <div class="payment-summary-row">
            <div>Items (3):</div>
            <div class="payment-summary-money">$42.75</div>
          </div>

          <div class="payment-summary-row">
            <div>Shipping &amp; handling:</div>
            <div class="payment-summary-money">$4.99</div>
          </div>

          <div class="payment-summary-row subtotal-row">
            <div>Total before tax:</div>
            <div class="payment-summary-money">$47.74</div>
          </div>

          <div class="payment-summary-row">
            <div>Estimated tax (10%):</div>
            <div class="payment-summary-money">$4.77</div>
          </div>

          <div class="payment-summary-row total-row">
            <div>Order total:</div>
            <div class="payment-summary-money">$52.51</div>
          </div>

          <button class="place-order-button button-primary">
            Place your order
          </button>
        </div>
      </div>
    </div>

    <script type="module" src="scripts/checkout.js"></script>
  </body>
</html>`

cart.js   `export let cart = JSON.parse(localStorage.getItem('cart'));

if (!cart) {
  cart = [{
    productId: 'e43638ce-6aa0-4b85-b27f-e1d07eb678c6',
    quantity: 2,
  }, {
    productId: '15b6fc6f-327a-4ec4-896f-486349e85a3d',
    quantity: 1
  }];
}

function saveToStorage() {
  localStorage.setItem('cart', JSON.stringify(cart));
}

export function addToCart(productId) {
  let matchingItem;

  cart.forEach((cartItem) => {
    if (productId === cartItem.productId) {
      matchingItem = cartItem;
    }
  });

  if (matchingItem) {
    matchingItem.quantity += 1;
  } else {
    cart.push({
      productId: productId,
      quantity: 1
    });
  }

  saveToStorage();
}

export function removeFromCart(productId) {
  const newCart = [];

  cart.forEach((cartItem) => {
    if (cartItem.productId !== productId) {
      newCart.push(cartItem);
    }
  });

  cart = newCart;

  saveToStorage();
}`

**Comment by nurhusenm** [comment]
I sent 3 files of codes pls check the github account

**Comment by Monisha-devoper** [comment]
> here is what am facing it in the console tab the check out page is not working pls simon simplify the tech world Uncaught TypeError: Cannot read properties of undefined (reading 'id') at checkout.js:20:48 at Array.forEach () at checkout.js:7:6



hai unknown,
am also faced the same problem last day now its resolved. i found that my browser is the problem some overloading issues..
things i followed first open your browser inside the vs code(extention browser) .
if its works corectly then follow these steps:
1.open google chrome.
2.go to the setting area and clear the cache memory and history data .then try loading page again .. all the best.

**Comment by hunganh26** [comment]
hello, have you resolved this problem yet. I've been stuck with the exact same problem for a bit. I also tried @Monisha-devoper suggestion but didnt seem to work.

**Comment by nurhusenm** [comment]
I stopped it since feb28 cause I decided to not follow yt tutorial,to
escape from tutorial hell,and I focused on building simple projects by my
self from scratch and I will build Amazon clone also inshallah from scratch
by my self, it's better for u too to focus on simple projects to be
confident on ur skills


Happy coding

**Comment by okontg** [comment]
i have sept over 5 days to figure out it,
the problem is naming the 'cart.push()' differently from the 'cart object {productId: '-----',
quantity: 0}'.

make  sure the cart .push, has the same name with your cart object.

**Comment by lon-C** [comment]
I had the same issue, the thing that sorted it for me is clearing the browser cache and deleting the local storage:
localStorage.clear(); just remove this line after the online page restarted.
